telescope:
  restart: always
  image: telescopeapp/telescope
  ports:
   - "8080:80"
  links:
   - mongo
  environment:
   - ROOT_URL=http://127.0.0.1
   - MONGO_URL=mongodb://mongo

mongo:
  restart: always
  image: mongo
  ports:
  - "27017:27017"
  - "28017:28017"
  command: mongod --rest

wordpress:
  restart: always
  image: wordpress
  ports:
    - "8081:80"
  env_file: ./wordpress.env

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
  - "./nginx.conf:/etc/nginx/nginx.conf:ro"
  links:
    - telescope
    - wordpress
